const SERVER_URL = ""
export const GET_BLOCK_META_URL = SERVER_URL + "/block-meta"
export const GET_PROJECT_URL = SERVER_URL + "project"
export const POST_PROJECT_URL = SERVER_URL + "project"
export const GET_WORKSPACE_URL = SERVER_URL + "workspace"
export const GET_VERSIONS_URL = SERVER_URL + "versions"